### PR TITLE
support init.lua files in include dirs

### PR DESCRIPTION
**Pull request by catwell**

### CODE REVIEW

**Comment by mihacooper** [comment]
Looking good, thanks for help!
We just need to tell about that in `README.md`. I think you can place it in `Usage.<modules>.Note`. Ok?

**Comment by catwell** [comment]
Maybe just complete the last sentence in "include" this way:

> Firstly it tries to find out the module using the current path and if it's not found LuaCC searches the module using each include path in specified order, as if `package.path` contained `/the/include/path/?.lua;/the/include/path/?/init.lua`.

**Comment by mihacooper** [comment]
Ok, that's good too

**Comment by catwell** [comment]
Done.

**Comment by mihacooper** [comment]
Ok, thanks for contribution!

**Pull request merged**
